version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "Africa/Cairo"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:15"
      timezone: "Africa/Cairo"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "softprops/action-gh-release"
        update-types:
          - "version-update:semver-major"
